version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Thanhluc@123
      MYSQL_DATABASE: tl_home
    ports:
      - '3307:3306'
    volumes:
      - ./data:/var/lib/mysql
