version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lt-home-be
    env_file:
      - .env.prod
    ports:
      - '80:3000'
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - '3308:3306'
    env_file:
      - .env.prod
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
